/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuitionRouteImport } from './routes/tuition'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as TeacherTimetableRouteImport } from './routes/teacher.timetable'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherGradesRouteImport } from './routes/teacher.grades'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeacherChatRouteImport } from './routes/teacher.chat'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as StudentTuitionRouteImport } from './routes/student.tuition'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentRetakeRegistrationRouteImport } from './routes/student.retake-registration'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCurriculumRouteImport } from './routes/student.curriculum'
import { Route as StudentCourseRegistrationRouteImport } from './routes/student.course-registration'
import { Route as StudentChatRouteImport } from './routes/student.chat'
import { Route as StudentAcademicResultsRouteImport } from './routes/student.academic-results'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminWorkflowRouteImport } from './routes/admin.workflow'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTimetablesRouteImport } from './routes/admin.timetables'
import { Route as AdminTeachingAssignmentsRouteImport } from './routes/admin.teaching-assignments'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSemestersRouteImport } from './routes/admin.semesters'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRegistrationPeriodsRouteImport } from './routes/admin.registration-periods'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPeriodsRouteImport } from './routes/admin.periods'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMajorsRouteImport } from './routes/admin.majors'
import { Route as AdminLandingRouteImport } from './routes/admin.landing'
import { Route as AdminFacultiesRouteImport } from './routes/admin.faculties'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin.enrollments'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCurriculumsRouteImport } from './routes/admin.curriculums'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminClassSectionsRouteImport } from './routes/admin.class-sections'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminAcademicResultsRouteImport } from './routes/admin.academic-results'
import { Route as TeacherClassesClassSectionIdStudentsRouteImport } from './routes/teacher.classes.$classSectionId.students'

const TuitionRoute = TuitionRouteImport.update({
  id: '/tuition',
  path: '/tuition',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGradesRoute = TeacherGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherChatRoute = TeacherChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentTuitionRoute = StudentTuitionRouteImport.update({
  id: '/tuition',
  path: '/tuition',
  getParentRoute: () => StudentRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRetakeRegistrationRoute =
  StudentRetakeRegistrationRouteImport.update({
    id: '/retake-registration',
    path: '/retake-registration',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCurriculumRoute = StudentCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCourseRegistrationRoute =
  StudentCourseRegistrationRouteImport.update({
    id: '/course-registration',
    path: '/course-registration',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentChatRoute = StudentChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAcademicResultsRoute = StudentAcademicResultsRouteImport.update({
  id: '/academic-results',
  path: '/academic-results',
  getParentRoute: () => StudentRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminWorkflowRoute = AdminWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetablesRoute = AdminTimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachingAssignmentsRoute =
  AdminTeachingAssignmentsRouteImport.update({
    id: '/teaching-assignments',
    path: '/teaching-assignments',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSemestersRoute = AdminSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationPeriodsRoute =
  AdminRegistrationPeriodsRouteImport.update({
    id: '/registration-periods',
    path: '/registration-periods',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeriodsRoute = AdminPeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMajorsRoute = AdminMajorsRouteImport.update({
  id: '/majors',
  path: '/majors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingRoute = AdminLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurriculumsRoute = AdminCurriculumsRouteImport.update({
  id: '/curriculums',
  path: '/curriculums',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassSectionsRoute = AdminClassSectionsRouteImport.update({
  id: '/class-sections',
  path: '/class-sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicResultsRoute = AdminAcademicResultsRouteImport.update({
  id: '/academic-results',
  path: '/academic-results',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherClassesClassSectionIdStudentsRoute =
  TeacherClassesClassSectionIdStudentsRouteImport.update({
    id: '/$classSectionId/students',
    path: '/$classSectionId/students',
    getParentRoute: () => TeacherClassesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/tuition': typeof TuitionRoute
  '/admin/academic-results': typeof AdminAcademicResultsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/class-sections': typeof AdminClassSectionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/curriculums': typeof AdminCurriculumsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/majors': typeof AdminMajorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/registration-periods': typeof AdminRegistrationPeriodsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/semesters': typeof AdminSemestersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-assignments': typeof AdminTeachingAssignmentsRoute
  '/admin/timetables': typeof AdminTimetablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/student/academic-results': typeof StudentAcademicResultsRoute
  '/student/chat': typeof StudentChatRoute
  '/student/course-registration': typeof StudentCourseRegistrationRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/retake-registration': typeof StudentRetakeRegistrationRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tuition': typeof StudentTuitionRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/articles/': typeof ArticlesIndexRoute
  '/teacher/classes/$classSectionId/students': typeof TeacherClassesClassSectionIdStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/tuition': typeof TuitionRoute
  '/admin/academic-results': typeof AdminAcademicResultsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/class-sections': typeof AdminClassSectionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/curriculums': typeof AdminCurriculumsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/majors': typeof AdminMajorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/registration-periods': typeof AdminRegistrationPeriodsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/semesters': typeof AdminSemestersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-assignments': typeof AdminTeachingAssignmentsRoute
  '/admin/timetables': typeof AdminTimetablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/student/academic-results': typeof StudentAcademicResultsRoute
  '/student/chat': typeof StudentChatRoute
  '/student/course-registration': typeof StudentCourseRegistrationRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/retake-registration': typeof StudentRetakeRegistrationRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tuition': typeof StudentTuitionRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/articles': typeof ArticlesIndexRoute
  '/teacher/classes/$classSectionId/students': typeof TeacherClassesClassSectionIdStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/tuition': typeof TuitionRoute
  '/admin/academic-results': typeof AdminAcademicResultsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/class-sections': typeof AdminClassSectionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/curriculums': typeof AdminCurriculumsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/majors': typeof AdminMajorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/registration-periods': typeof AdminRegistrationPeriodsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/semesters': typeof AdminSemestersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/teaching-assignments': typeof AdminTeachingAssignmentsRoute
  '/admin/timetables': typeof AdminTimetablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/student/academic-results': typeof StudentAcademicResultsRoute
  '/student/chat': typeof StudentChatRoute
  '/student/course-registration': typeof StudentCourseRegistrationRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/retake-registration': typeof StudentRetakeRegistrationRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tuition': typeof StudentTuitionRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/articles/': typeof ArticlesIndexRoute
  '/teacher/classes/$classSectionId/students': typeof TeacherClassesClassSectionIdStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/articles'
    | '/contact'
    | '/login'
    | '/news'
    | '/programs'
    | '/scholarships'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/tuition'
    | '/admin/academic-results'
    | '/admin/chat'
    | '/admin/class-sections'
    | '/admin/courses'
    | '/admin/curriculums'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/faculties'
    | '/admin/landing'
    | '/admin/majors'
    | '/admin/notifications'
    | '/admin/periods'
    | '/admin/profile'
    | '/admin/registration-periods'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/semesters'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/teaching-assignments'
    | '/admin/timetables'
    | '/admin/users'
    | '/admin/workflow'
    | '/articles/$slug'
    | '/student/academic-results'
    | '/student/chat'
    | '/student/course-registration'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/grades'
    | '/student/notifications'
    | '/student/profile'
    | '/student/retake-registration'
    | '/student/schedule'
    | '/student/tuition'
    | '/teacher/attendance'
    | '/teacher/chat'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/grades'
    | '/teacher/profile'
    | '/teacher/timetable'
    | '/articles/'
    | '/teacher/classes/$classSectionId/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/contact'
    | '/login'
    | '/news'
    | '/programs'
    | '/scholarships'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/tuition'
    | '/admin/academic-results'
    | '/admin/chat'
    | '/admin/class-sections'
    | '/admin/courses'
    | '/admin/curriculums'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/faculties'
    | '/admin/landing'
    | '/admin/majors'
    | '/admin/notifications'
    | '/admin/periods'
    | '/admin/profile'
    | '/admin/registration-periods'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/semesters'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/teaching-assignments'
    | '/admin/timetables'
    | '/admin/users'
    | '/admin/workflow'
    | '/articles/$slug'
    | '/student/academic-results'
    | '/student/chat'
    | '/student/course-registration'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/grades'
    | '/student/notifications'
    | '/student/profile'
    | '/student/retake-registration'
    | '/student/schedule'
    | '/student/tuition'
    | '/teacher/attendance'
    | '/teacher/chat'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/grades'
    | '/teacher/profile'
    | '/teacher/timetable'
    | '/articles'
    | '/teacher/classes/$classSectionId/students'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/articles'
    | '/contact'
    | '/login'
    | '/news'
    | '/programs'
    | '/scholarships'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/tuition'
    | '/admin/academic-results'
    | '/admin/chat'
    | '/admin/class-sections'
    | '/admin/courses'
    | '/admin/curriculums'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/faculties'
    | '/admin/landing'
    | '/admin/majors'
    | '/admin/notifications'
    | '/admin/periods'
    | '/admin/profile'
    | '/admin/registration-periods'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/semesters'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/teaching-assignments'
    | '/admin/timetables'
    | '/admin/users'
    | '/admin/workflow'
    | '/articles/$slug'
    | '/student/academic-results'
    | '/student/chat'
    | '/student/course-registration'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/grades'
    | '/student/notifications'
    | '/student/profile'
    | '/student/retake-registration'
    | '/student/schedule'
    | '/student/tuition'
    | '/teacher/attendance'
    | '/teacher/chat'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/grades'
    | '/teacher/profile'
    | '/teacher/timetable'
    | '/articles/'
    | '/teacher/classes/$classSectionId/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  ProgramsRoute: typeof ProgramsRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TuitionRoute: typeof TuitionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuition': {
      id: '/tuition'
      path: '/tuition'
      fullPath: '/tuition'
      preLoaderRoute: typeof TuitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/grades': {
      id: '/teacher/grades'
      path: '/grades'
      fullPath: '/teacher/grades'
      preLoaderRoute: typeof TeacherGradesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/chat': {
      id: '/teacher/chat'
      path: '/chat'
      fullPath: '/teacher/chat'
      preLoaderRoute: typeof TeacherChatRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/tuition': {
      id: '/student/tuition'
      path: '/tuition'
      fullPath: '/student/tuition'
      preLoaderRoute: typeof StudentTuitionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/retake-registration': {
      id: '/student/retake-registration'
      path: '/retake-registration'
      fullPath: '/student/retake-registration'
      preLoaderRoute: typeof StudentRetakeRegistrationRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/curriculum': {
      id: '/student/curriculum'
      path: '/curriculum'
      fullPath: '/student/curriculum'
      preLoaderRoute: typeof StudentCurriculumRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/course-registration': {
      id: '/student/course-registration'
      path: '/course-registration'
      fullPath: '/student/course-registration'
      preLoaderRoute: typeof StudentCourseRegistrationRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/chat': {
      id: '/student/chat'
      path: '/chat'
      fullPath: '/student/chat'
      preLoaderRoute: typeof StudentChatRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/academic-results': {
      id: '/student/academic-results'
      path: '/academic-results'
      fullPath: '/student/academic-results'
      preLoaderRoute: typeof StudentAcademicResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/workflow': {
      id: '/admin/workflow'
      path: '/workflow'
      fullPath: '/admin/workflow'
      preLoaderRoute: typeof AdminWorkflowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetables': {
      id: '/admin/timetables'
      path: '/timetables'
      fullPath: '/admin/timetables'
      preLoaderRoute: typeof AdminTimetablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teaching-assignments': {
      id: '/admin/teaching-assignments'
      path: '/teaching-assignments'
      fullPath: '/admin/teaching-assignments'
      preLoaderRoute: typeof AdminTeachingAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/semesters': {
      id: '/admin/semesters'
      path: '/semesters'
      fullPath: '/admin/semesters'
      preLoaderRoute: typeof AdminSemestersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registration-periods': {
      id: '/admin/registration-periods'
      path: '/registration-periods'
      fullPath: '/admin/registration-periods'
      preLoaderRoute: typeof AdminRegistrationPeriodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/periods': {
      id: '/admin/periods'
      path: '/periods'
      fullPath: '/admin/periods'
      preLoaderRoute: typeof AdminPeriodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/majors': {
      id: '/admin/majors'
      path: '/majors'
      fullPath: '/admin/majors'
      preLoaderRoute: typeof AdminMajorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing': {
      id: '/admin/landing'
      path: '/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AdminLandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/curriculums': {
      id: '/admin/curriculums'
      path: '/curriculums'
      fullPath: '/admin/curriculums'
      preLoaderRoute: typeof AdminCurriculumsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/class-sections': {
      id: '/admin/class-sections'
      path: '/class-sections'
      fullPath: '/admin/class-sections'
      preLoaderRoute: typeof AdminClassSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academic-results': {
      id: '/admin/academic-results'
      path: '/academic-results'
      fullPath: '/admin/academic-results'
      preLoaderRoute: typeof AdminAcademicResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/classes/$classSectionId/students': {
      id: '/teacher/classes/$classSectionId/students'
      path: '/$classSectionId/students'
      fullPath: '/teacher/classes/$classSectionId/students'
      preLoaderRoute: typeof TeacherClassesClassSectionIdStudentsRouteImport
      parentRoute: typeof TeacherClassesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcademicResultsRoute: typeof AdminAcademicResultsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminClassSectionsRoute: typeof AdminClassSectionsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminCurriculumsRoute: typeof AdminCurriculumsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminLandingRoute: typeof AdminLandingRoute
  AdminMajorsRoute: typeof AdminMajorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPeriodsRoute: typeof AdminPeriodsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRegistrationPeriodsRoute: typeof AdminRegistrationPeriodsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSemestersRoute: typeof AdminSemestersRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTeachingAssignmentsRoute: typeof AdminTeachingAssignmentsRoute
  AdminTimetablesRoute: typeof AdminTimetablesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkflowRoute: typeof AdminWorkflowRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicResultsRoute: AdminAcademicResultsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminClassSectionsRoute: AdminClassSectionsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminCurriculumsRoute: AdminCurriculumsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminLandingRoute: AdminLandingRoute,
  AdminMajorsRoute: AdminMajorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPeriodsRoute: AdminPeriodsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRegistrationPeriodsRoute: AdminRegistrationPeriodsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSemestersRoute: AdminSemestersRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTeachingAssignmentsRoute: AdminTeachingAssignmentsRoute,
  AdminTimetablesRoute: AdminTimetablesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowRoute: AdminWorkflowRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface StudentRouteChildren {
  StudentAcademicResultsRoute: typeof StudentAcademicResultsRoute
  StudentChatRoute: typeof StudentChatRoute
  StudentCourseRegistrationRoute: typeof StudentCourseRegistrationRoute
  StudentCurriculumRoute: typeof StudentCurriculumRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRetakeRegistrationRoute: typeof StudentRetakeRegistrationRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentTuitionRoute: typeof StudentTuitionRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAcademicResultsRoute: StudentAcademicResultsRoute,
  StudentChatRoute: StudentChatRoute,
  StudentCourseRegistrationRoute: StudentCourseRegistrationRoute,
  StudentCurriculumRoute: StudentCurriculumRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRetakeRegistrationRoute: StudentRetakeRegistrationRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentTuitionRoute: StudentTuitionRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherClassesRouteChildren {
  TeacherClassesClassSectionIdStudentsRoute: typeof TeacherClassesClassSectionIdStudentsRoute
}

const TeacherClassesRouteChildren: TeacherClassesRouteChildren = {
  TeacherClassesClassSectionIdStudentsRoute:
    TeacherClassesClassSectionIdStudentsRoute,
}

const TeacherClassesRouteWithChildren = TeacherClassesRoute._addFileChildren(
  TeacherClassesRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherChatRoute: typeof TeacherChatRoute
  TeacherClassesRoute: typeof TeacherClassesRouteWithChildren
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherGradesRoute: typeof TeacherGradesRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherChatRoute: TeacherChatRoute,
  TeacherClassesRoute: TeacherClassesRouteWithChildren,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherGradesRoute: TeacherGradesRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdmissionsRoute: AdmissionsRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  ProgramsRoute: ProgramsRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TuitionRoute: TuitionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
